---
galaxy_info:
  author: Oluf Lorenzen
  description: server-essentials
  company: your company (optional)
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
dependencies: []
