---
# defaults file for exim4-dovecot-mailer

mail_domains:
  - name: example.com
    aliases:
#      # forward to another e-mail-address
      - www: "alima@example.org"
#  	  # deliver mail to the mailbox "another-mailaccount"
      - root: another-mailaccount
#  	  # perm-reject mails with the message: "harrharr"
      - postmaster: ":fail: harrharr"
#  	  # blackhole messages (e.g. accept and delete)
      - abuse : ":blackhole:"
#  	  # pass the mail to "/some/command" with the localpart as argument
      - hostmaster: "|/some/command ${local_part}"

exim4_dc_eximconfig_configtype: internet
# FIXME amke this dynamic!
exim4_dc_other_hostnames: "brakhane.net : brakhane.org : anjaroot.net : failedprojects.de : lpconnection.net"
exim4_dc_local_interfaces: '127.0.0.1 ; ::1'
exim4_dc_readhost: ''
exim4_dc_relay_domains: ''
exim4_dc_minimaldns: 'false'
exim4_dc_relay_nets: ''
exim4_dc_smarthost: ''
exim4_CFILEMODE: '644'
exim4_dc_use_split_config: 'true'
exim4_dc_hide_mailname: ''
exim4_dc_mailname_in_oh: 'true'
exim4_dc_localdelivery: 'mail_spool'
exim4_enable_verify_sender_callout: 'true'

dovecot_auth_verbose: 'yes'
dovecot_auth_verbose_passwords: 'yes'
dovecot_auth_debug: 'yes'
dovecot_auth_debug_passwords: 'yes'
dovecot_mail_debug: 'no'
dovecot_verbose_ssl: 'no'
dovecot_mail_dir: '/var/vmail'
dovecot_mail_subdir: '%d/%n'
dovecot_mail_location: 'maildir:{{ dovecot_mail_dir }}/{{ dovecot_mail_subdir }}'
dovecot_imaps_port: '993'
dovecot_pop3s_port: '995'
dovecot_ssl_cert: '/etc/dovecot/dovecot.pem'
dovecot_ssl_privkey: '/etc/dovecot/private/dovecot.key'
dovecot_ssl_dhparam_length: '4096'
dovecot_ssl_ciphers: '!SSLv2 !SSLv3'
dovecot_ssl_cipher_list: 'AES128+EECDH:AES128+EDH'
dovecot_ssl_prefer_server_ciphers: 'yes'
dovecot_postmaster_address: 'postmaster@%d'

clamd_usigs_reload_dbs: 'yes'

sqlite_init_file: 'files/sqlite/init-clean.sqlite'
sqlite_user_file: 'files/sqlite/user.sqlite'

local_ssl_cert: 'files/ssl/ssl-cert-snakeoil.pem'
local_ssl_privkey: 'files/ssl/ssl-cert-snakeoil.key'
