---
# defaults file for exim4-dovecot-mailer

mail_domains:
  - name: example.com
    aliases:
      # forward to another e-mail-address
      - www: alima@example.org
  	  # deliver mail to the mailbox "another-mailaccount"
      - root: another-mailaccount
  	  # perm-reject mails with the message: "harrharr"
      - postmaster: ":fail: harrharr"
  	  # blackhole messages (e.g. accept and delete)
      - abuse : ":blackhole:"
  	  # pass the mail to "/some/command" with the localpart as argument
      - hostmaster: "|/some/command ${local_part}"
