---
# FIXME why check mta_installed?
- name: check if a mail transfer agent is installed
  command: grep-status -sPackage -sProvides -FProvides "mail-transport-agent" -q
  register: mta_installed
  ignore_errors: True

- name: install exim4-daemon-heavy
  apt: pkg=exim4-daemon-heavy state=installed

- name: install spf-tools-perl
  apt: pkg=spf-tools-perl state=installed

- name: Update config etc/default/exim4.j2
  template: src=etc/default/exim4.j2.j2 dest=/etc/default/exim4.j2
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/update-exim4.conf.conf
  template: src=etc/exim4/update-exim4.conf.conf.j2 dest=/etc/exim4/update-exim4.conf.conf
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

#- name: Update config etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases
#  template: src=etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases.j2 dest=/etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases
#  notify:
#    - update exim4.conf
#    - restart exim4
#    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny
  template: src=etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny.j2 dest=/etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/auth/40_local-dovecot-auth
  template: src=etc/exim4/conf.d/auth/40_local-dovecot-auth.j2 dest=/etc/exim4/conf.d/auth/40_local-dovecot-auth
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/data-check-scan-acl
  template: src=etc/exim4/data-check-scan-acl.j2 dest=/etc/exim4/data-check-scan-acl
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/local-rcpt-acl
  template: src=etc/exim4/local-rcpt-acl.j2 dest=/etc/exim4/local-rcpt-acl
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/acl/30_exim4-config_check_rcpt
  template: src=etc/exim4/conf.d/acl/30_exim4-config_check_rcpt.j2 dest=/etc/exim4/conf.d/acl/30_exim4-config_check_rcpt
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/main/001_local_config
  template: src=etc/exim4/conf.d/main/001_local_config.j2 dest=/etc/exim4/conf.d/main/001_local_config
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/main/000_queue_only
  template: src=etc/exim4/conf.d/main/000_queue_only.j2 dest=/etc/exim4/conf.d/main/000_queue_only
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/main/002_local-sql
  template: src=etc/exim4/conf.d/main/002_local-sql.j2 dest=/etc/exim4/conf.d/main/002_local-sql
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/router/210_local-sqlite
  template: src=etc/exim4/conf.d/router/210_local-sqlite.j2 dest=/etc/exim4/conf.d/router/210_local-sqlite
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/router/899_local-user-suffix-rewrite
  template: src=etc/exim4/conf.d/router/899_local-user-suffix-rewrite.j2 dest=/etc/exim4/conf.d/router/899_local-user-suffix-rewrite
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

#- name: Update config etc/exim4/conf.d/router/900_exim4-config_local_user
#  template: src=etc/exim4/conf.d/router/900_exim4-config_local_user.j2 dest=/etc/exim4/conf.d/router/900_exim4-config_local_user
#  notify:
#    - update exim4.conf
#    - restart exim4
#    - gitmaintainer commit

#- name: Update config etc/exim4/conf.d/router/901_local-user-vmail
#  template: src=etc/exim4/conf.d/router/901_local-user-vmail.j2 dest=/etc/exim4/conf.d/router/901_local-user-vmail
#  notify:
#    - update exim4.conf
#    - restart exim4
#    - gitmaintainer commit

- name: Update config etc/exim4/conf.d/transport/40_local-dovecot-lmtp
  template: src=etc/exim4/conf.d/transport/40_local-dovecot-lmtp.j2 dest=/etc/exim4/conf.d/transport/40_local-dovecot-lmtp
  notify:
    - update exim4.conf
    - restart exim4
    - gitmaintainer commit

- name: make sure optional exim-configs exist
  # FIXME make this a template, filled from configs or sqlite
  file: path=/etc/exim4/local_recipient_whitelist state=touch mode="u=rw,g=r,o=r"
  file: path=/etc/exim4/local_sender_whitelist_spam state=touch mode="u=rw,g=r,o=r"
  notify:
    - gitmaintainer commit

- name: update ssl-cert
  synchronize: src={{ local_ssl_cert }} dest={{ exim_ssl_cert }}

- name: set ssl-cert permissions
  file: path={{ exim_ssl_cert }} state=file owner=root group=Debian-exim mode="u=r,g=r,o="

- name: create ssl-private-dir
  file: path={{ exim_ssl_private_dir }} state=directory owner=root group=Debian-exim mode=0750

- name: update ssl-key
  synchronize: src={{ local_ssl_privkey }} dest={{ exim_ssl_privkey }}

- name: set ssl-key permissions
  file: path={{ exim_ssl_privkey }} state=file owner=root group=Debian-exim mode="u=r,g=r,o="
