---
- name: check if a mail transfer agent is installed
  command: grep-status -sPackage -sProvides -FProvides "mail-transport-agent" -q
  register: mta_installed
  ignore_errors: True

- name: install exim4-daemon-heavy
  apt: pkg=exim4-daemon-heavy state=installed
  environment:
    GIT_AUTOCOMMIT: "true"
    GIT_COMMITTER_NAME: "ansible on {{lookup('pipe','hostname -f')}}"
    GIT_COMMITTER_EMAIL: "ansible@{{ lookup('pipe','hostname -f') }}"

- name: install spf-tools-perl
  apt: pkg=spf-tools-perl state=installed
  environment:
    GIT_AUTOCOMMIT: "true"
    GIT_COMMITTER_NAME: "ansible on {{lookup('pipe','hostname -f')}}"
    GIT_COMMITTER_EMAIL: "ansible@{{ lookup('pipe','hostname -f') }}"


- name: Update config etc/exim4/update-exim4.conf.conf
  template: src=etc/exim4/update-exim4.conf.conf.j2 dest=/etc/exim4/update-exim4.conf.conf

- name: Update config etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases
  template: src=etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases.j2 dest=/etc/exim4/conf.d/router/350_mafia-server-config_vdom_aliases

- name: Update config etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny
  template: src=etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny.j2 dest=/etc/exim4/conf.d/acl/22_local-config_selective_dnsbl_greylist_deny

- name: Update config etc/exim4/conf.d/acl/30_exim4-config_check_rcpt
  template: src=etc/exim4/conf.d/acl/30_exim4-config_check_rcpt.j2 dest=/etc/exim4/conf.d/acl/30_exim4-config_check_rcpt

- name: Update config etc/exim4/conf.d/main/001_local_config
  template: src=etc/exim4/conf.d/main/001_local_config.j2 dest=/etc/exim4/conf.d/main/001_local_config

- name: Update config etc/exim4/conf.d/main/000_queue_only
  template: src=etc/exim4/conf.d/main/000_queue_only.j2 dest=/etc/exim4/conf.d/main/000_queue_only

- name: restart exim4
  service: name=exim4 state=restarted
