---
- name: install spamassassin
  apt: pkg=spamassassin state=installed

- name: Update config etc/default/spamassassin
  template: src=etc/default/spamassassin.j2 dest=/etc/default/spamassassin
  notify:
    - restart spamassassin
    - gitmaintainer commit

- name: Update config etc/spamassassin/local.cf
  template: src=etc/spamassassin/local.cf.j2 dest=/etc/spamassassin/local.cf
  notify:
    - check spamassassin.conf
    - restart spamassassin
    - gitmaintainer commit

