---
- name: install spamassassin
  apt: pkg=spamassassin state=installed
  environment:
    GIT_AUTOCOMMIT: "true"
    GIT_COMMITTER_NAME: "ansible on {{lookup('pipe','hostname -f')}}"
    GIT_COMMITTER_EMAIL: "ansible@{{ lookup('pipe','hostname -f') }}"

- name: Update config etc/default/spamassassin
  template: src=etc/default/spamassassin.j2 dest=/etc/default/spamassassin
  register: [ do-gitmaintainer-commit, do-sa-restart ]

- name: Update config etc/spamassassin/local.cf
  template: src=etc/spamassassin/local.cf.j2 dest=/etc/spamassassin/local.cf
  notify: update spamassassin.conf
  register: [ do-gitmaintainer-commit, do-sa-restart ]

- name: restart spamassassin
  service: name=spamassassin state=restarted
  when: do-sa-restart
